apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-app
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-master-service
spec:
  selector:
    app: hello-app
  ports:
    - port: 8765
      targetPort: 8080
  type: LoadBalancer